#!/bin/bash
set -e

DOWNSAMPLE_FACTOR=${DOWNSAMPLE_FACTOR-1}
TABLE_SIZE=${TABLE_SIZE-128}
cat > build/platform.lib <<EOF
SR = 48000 / $DOWNSAMPLE_FACTOR;
BS = 1;
tablesize = $TABLE_SIZE;
EOF

FILE=${1-examples/sawtooth.dsp}

export PLATFORMDIR=~/prog/others/logue-sdk/platform/minilogue-xd
mkdir -p build
faust -a src/logue_metadata.arch -I build -uim $FILE > build/oscillator_metadata.cpp
(echo "#define DOWNSAMPLE_FACTOR $DOWNSAMPLE_FACTOR";
 faust -a src/logue.arch -fm $(pwd)/src/fastmath.cpp -I build -nvi -exp10 -ct 0 -mapp -os $FILE) > build/oscillator.cpp
g++ -std=c++20 build/oscillator_metadata.cpp -o build/oscillator_metadata
build/oscillator_metadata build/inputs.h build/manifest.json
make -C logue-project install
