#!/bin/bash
set -e

SR_DIVIDER=${SR_DIVIDER-1}
TABLE_SIZE=${TABLE_SIZE-128}
cat > build/platform.lib <<EOF
SR = 48000 / $SR_DIVIDER;
BS = min(64, max(1, fvariable(int count, <math.h>)));
tablesize = $TABLE_SIZE;
EOF

FILE=${1-examples/sawtooth.dsp}

export PLATFORMDIR=~/prog/others/logue-sdk/platform/minilogue-xd
mkdir -p build
faust -a src/logue_metadata.arch -I build -uim $FILE > build/oscillator_metadata.cpp
(echo "#define SR_DIVIDER $SR_DIVIDER";
 faust -a src/logue.arch -fm $(pwd)/src/fastmath.cpp -I build -nvi -exp10 -ct 0 -mapp $FILE) > build/oscillator.cpp
g++ -std=c++20 build/oscillator_metadata.cpp -o build/oscillator_metadata
build/oscillator_metadata build/inputs.h build/manifest.json
make -C logue-project install
